import type { Metadata } from "next";
import { LeagueBookingProvider } from "@/components/league/booking-context";

/**
 * Game On Multisports League — standalone landing flow.
 *
 * Intentionally chrome-free: no sticky brand header, no bottom tab bar and no
 * footer. Each screen carries its own inline content and a sticky action bar,
 * so the whole flow reads as a single landing page a walk-in can book from.
 *
 * The screens below this layout are the copies generated by
 * `scripts/create-multisports-league-flow.mjs`; the hand-written landing and
 * category pages live in `src/components/league/`.
 */

export const metadata: Metadata = {
  title: {
    default: "Game On Multisports League — Book Your Slot",
    template: "%s | Game On Multisports League",
  },
  description:
    "Book a slot in the Game On Multisports League — badminton, pickleball, box cricket 7v7 and football 6v6 at Sector 70, Gurugram. Pick your category, see every open slot and book in a few taps.",
  openGraph: {
    title: "Game On Multisports League",
    description:
      "4 sports, 8 categories, live slot availability. Pick a category, choose a slot and book.",
    siteName: "Game On",
    locale: "en_IN",
    type: "website",
  },
};

export default function MultisportsLeagueLayout({ children }: { children: React.ReactNode }) {
  return (
    <LeagueBookingProvider>
      <div className="relative min-h-dvh bg-go-black">
        {/* Ambient brand glow — the only decoration this flow shares with the app */}
        <div
          aria-hidden
          className="pointer-events-none fixed inset-x-0 top-0 z-0 h-[420px]"
          style={{
            background:
              "radial-gradient(120% 100% at 50% 0%, rgba(245,166,35,0.13) 0%, rgba(11,11,12,0) 62%)",
          }}
        />

        <main className="relative z-10 mx-auto w-full max-w-6xl px-4 pb-36 pt-6 sm:px-6 lg:pb-12 lg:pt-10">
          {children}
        </main>
      </div>
    </LeagueBookingProvider>
  );
}
